add_newline = true

[package]
disabled = true

[aws.region_aliases]
ap-northeast-1 = "jp"

[memory_usage]
disabled = false
threshold = -1
style = "bold dimmed blue"
format = "[ram${ram_pct}/swap${swap_pct}]($style) "

[git_status]
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
